export const CHANGE_MONTH = 'CHANGE_MONTH';
export const GET_PLANNED_EVENTS_REQUEST = 'GET_PLANNED_EVENTS_REQUEST';
export const GET_PLANNED_EVENTS_SUCCESS = 'GET_PLANNED_EVENTS_SUCCESS';
export const GET_PLANNED_EVENTS_FAIL = 'GET_PLANNED_EVENTS_FAIL';
export const OPEN_DAY_DETAILS = 'OPEN_DAY_DETAILS'