export const GET_MAIN_MENU_BEGIN = 'GET_MAIN_MENU_BEGIN';
export const GET_MAIN_MENU_SUCCESS = 'GET_MAIN_MENU_SUCCESS';
export const GET_MAIN_MENU_FAIL = 'GET_MAIN_MENU_FAIL';
export const GET_MAIN_MENU_CANCELLED = 'GET_MAIN_MENU_CANCELLED';
export const SET_ACTIVE_CONTENT = 'SET_ACTIVE_CONTENT';