import { MODULE_ACTION_NAMESPACE } from '../../common/constants/exercisesActionTypes';

export const GET_LIST_BEGIN = `${MODULE_ACTION_NAMESPACE}_GET_LIST_BEGIN`;
export const GET_LIST_SUCCESS = `${MODULE_ACTION_NAMESPACE}_GET_LIST_SUCCESS`;
export const GET_LIST_FAIL = `${MODULE_ACTION_NAMESPACE}_GET_LIST_FAIL`;
export const GET_LIST_CANCELLED = `${MODULE_ACTION_NAMESPACE}_GET_LIST_CANCELLED`;
