import { MODULE_ACTION_NAMESPACE } from '../../common/constants/exercisesActionTypes';

const ENTITY_ACTION_NAMESPACE = `${MODULE_ACTION_NAMESPACE}_LIST`;

export const GET_LIST_BEGIN = `${ENTITY_ACTION_NAMESPACE}_GET_LIST_BEGIN`;
export const GET_LIST_SUCCESS = `${ENTITY_ACTION_NAMESPACE}_GET_LIST_SUCCESS`;
export const GET_LIST_FAIL = `${ENTITY_ACTION_NAMESPACE}_GET_LIST_FAIL`;
export const GET_LIST_CANCELLED = `${ENTITY_ACTION_NAMESPACE}_GET_LIST_CANCELLED`;
export const SET_SEARCH_STRING = `${ENTITY_ACTION_NAMESPACE}_SET_SEARCH_STRING`;
export const CLEAR_FORM = `${ENTITY_ACTION_NAMESPACE}_CLEAR_FORM`;
